// evaBoard for the Mac: a menu-bar app that keeps the same clipboard list as the evaBoard keyboard
// on the phone, over the home Wi-Fi.
//
// Text and pictures travel. What is copied on the Mac joins the list (and shows up in the keyboard's history); a fresh copy
// on the phone is put on the Mac's clipboard at once, so Cmd+V pastes it. Clicking an item copies
// it here. Deleting, clearing and pinning are repeated on the phone, and the phone's on the Mac.
// Things a password manager marks as concealed are never taken from the Mac's clipboard.
//
// Built by mac/build.sh (no Xcode project): swiftc, an Info.plist, an ad-hoc signature.

import AppKit
import CryptoKit
import UniformTypeIdentifiers
import ServiceManagement
import SwiftUI

final class Model: ObservableObject {
    static let shared = Model()

    let store: Store
    private(set) var link: Link!
    @Published private(set) var code: String
    @Published var copiedId: String?

    private let folder: URL
    var folderURL: URL { folder }
    private var lastChange = NSPasteboard.general.changeCount
    private var ownChange = -1
    private var watcher: Timer?
    // pictures copied on the phone just now whose bytes are still on their way
    private var freshPictures: Set<String> = []
    // files from the phone on their way in, part by part
    private final class Inbound {
        let item: SyncItem
        let fresh: Bool
        let temp: URL
        let handle: FileHandle
        var hasher = SHA256()
        var next = 0
        init?(item: SyncItem, fresh: Bool, folder: URL) {
            self.item = item
            self.fresh = fresh
            temp = folder.appendingPathComponent(item.id)
            FileManager.default.createFile(atPath: temp.path, contents: nil)
            guard let handle = try? FileHandle(forWritingTo: temp) else { return nil }
            self.handle = handle
        }
    }
    private var inbound: [String: Inbound] = [:]
    // a file's id is the hash of its content: worked out once per file version
    private var fileIds: [String: String] = [:]
    private static let part = 512 * 1024
    private static let maxFile: Int64 = 2 * 1024 * 1024 * 1024

    static let maxPicture = 20 * 1024 * 1024
    static let jpeg = NSPasteboard.PasteboardType("public.jpeg")

    private static let skippedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    private init() {
        folder = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("evaBoard", isDirectory: true)
        try? FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        let codeFile = folder.appendingPathComponent("pairing-code.txt")
        if let saved = try? String(contentsOf: codeFile, encoding: .utf8).trimmingCharacters(in: .whitespacesAndNewlines),
           saved.count == 19 {
            code = saved
        } else {
            let made = PairingCode.make()
            try? made.write(to: codeFile, atomically: true, encoding: .utf8)
            code = made
        }
        store = Store(folder: folder)
        link = Link(code: code, snapshot: { [unowned self] in
            SyncMessage(t: "snapshot", items: Array(self.store.items.values), gone: self.store.gone)
        }, onMessage: { [unowned self] message, peer in
            self.handle(message, from: peer)
        })
        link.onPeerGone = { [unowned self] in self.peerGone() }
        link.start()
        watcher = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [unowned self] _ in self.checkPasteboard() }
    }

    // MARK: the phone

    private func handle(_ message: SyncMessage, from peer: Peer) {
        switch message.t {
        case "snapshot":
            if let marks = message.gone { store.apply(gone: marks) }
            var needed: [String] = []
            for item in message.items ?? [] where store.apply(upsert: item) {
                link.broadcast(SyncMessage(t: "upsert", item: item, fresh: false), except: peer)
                if item.kind == "image" && !store.hasBlob(item.id) { needed.append(item.id) }
                if item.kind == "file" && store.fileURL(item.id) == nil && startInbound(item, fresh: false) { needed.append(item.id) }
            }
            if !needed.isEmpty { peer.send(SyncMessage(t: "need", ids: needed)) }
        case "upsert":
            guard let item = message.item, store.apply(upsert: item) else { return }
            link.broadcast(SyncMessage(t: "upsert", item: item, fresh: message.fresh), except: peer)
            let fresh = message.fresh == true && item.ts > nowMs() - 60_000
            if item.kind == "file" && store.fileURL(item.id) == nil {
                // the file's content follows in parts; it lands in Downloads and, if fresh, on the clipboard
                if startInbound(item, fresh: fresh) { peer.send(SyncMessage(t: "need", ids: [item.id])) }
            } else if item.kind == "image" && !store.hasBlob(item.id) {
                // the picture's bytes follow on request; it goes on the clipboard once they are here
                if fresh { freshPictures.insert(item.id) }
                peer.send(SyncMessage(t: "need", ids: [item.id]))
            } else if fresh {
                // copied on the phone just now: ready for Cmd+V here
                put(item, own: true)
            }
        case "gone":
            guard let marks = message.gone else { return }
            store.apply(gone: marks)
            link.broadcast(SyncMessage(t: "gone", gone: marks), except: peer)
        case "need":
            for id in message.ids ?? [] {
                if let url = store.fileURL(id) {
                    stream(id, from: url, to: peer)
                } else if let data = store.blob(id) {
                    peer.send(SyncMessage(t: "blob", id: id, data: data.base64EncodedString()))
                }
            }
        case "part":
            receivePart(message)
        case "blob":
            guard let id = message.id, let encoded = message.data, let data = Data(base64Encoded: encoded),
                  store.items[id] != nil, store.saveBlob(id, data) else { return }
            if freshPictures.remove(id) != nil, let item = store.items[id] { put(item, own: true) }
        default:
            break
        }
    }

    // MARK: files

    private func startInbound(_ item: SyncItem, fresh: Bool) -> Bool {
        if inbound[item.id] != nil { return false }
        if let size = item.size, size > Model.maxFile { return false }
        let folder = folderURL.appendingPathComponent("incoming", isDirectory: true)
        try? FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        guard let job = Inbound(item: item, fresh: fresh, folder: folder) else { return false }
        inbound[item.id] = job
        return true
    }

    private func receivePart(_ message: SyncMessage) {
        guard let id = message.id, let job = inbound[id] else { return }
        guard message.seq == job.next, let data = Data(base64Encoded: message.data ?? "") else {
            // a part went missing: drop it, the next connection asks again
            dropInbound(id)
            return
        }
        job.hasher.update(data: data)
        job.handle.write(data)
        job.next += 1
        guard message.last == true else { return }
        inbound[id] = nil
        try? job.handle.close()
        let hash = "f" + String(job.hasher.finalize().map { String(format: "%02x", $0) }.joined().prefix(32))
        guard hash == id, store.items[id] != nil else { try? FileManager.default.removeItem(at: job.temp); return }
        let target = uniqueDownload(job.item.text.isEmpty ? "file" : job.item.text)
        do {
            try FileManager.default.moveItem(at: job.temp, to: target)
        } catch {
            try? FileManager.default.removeItem(at: job.temp)
            return
        }
        fileIds[fileKey(target)] = id
        store.setPath(id, target)
        if job.fresh, let item = store.items[id] { put(item, own: true) }
    }

    private func dropInbound(_ id: String) {
        guard let job = inbound.removeValue(forKey: id) else { return }
        try? job.handle.close()
        try? FileManager.default.removeItem(at: job.temp)
    }

    func peerGone() {
        for id in Array(inbound.keys) { dropInbound(id) }
    }

    private func uniqueDownload(_ name: String) -> URL {
        let downloads = FileManager.default.urls(for: .downloadsDirectory, in: .userDomainMask)[0]
        let safe = name.replacingOccurrences(of: "/", with: "_")
        var url = downloads.appendingPathComponent(safe)
        let base = (safe as NSString).deletingPathExtension
        let ext = (safe as NSString).pathExtension
        var n = 2
        while FileManager.default.fileExists(atPath: url.path) {
            url = downloads.appendingPathComponent(ext.isEmpty ? "\(base) (\(n))" : "\(base) (\(n)).\(ext)")
            n += 1
        }
        return url
    }

    /** Sends a file in parts, each after the one before has gone out. */
    private func stream(_ id: String, from url: URL, to peer: Peer) {
        guard let handle = try? FileHandle(forReadingFrom: url) else { return }
        var seq = 0
        var current = handle.readData(ofLength: Model.part)
        func step() {
            // one part read ahead, so the last part can say it is the last
            let next = current.count == Model.part ? handle.readData(ofLength: Model.part) : Data()
            let last = next.isEmpty
            peer.send(SyncMessage(t: "part", id: id, data: current.base64EncodedString(), seq: seq, last: last)) {
                if last {
                    try? handle.close()
                } else {
                    current = next
                    seq += 1
                    step()
                }
            }
        }
        step()
    }

    private func fileKey(_ url: URL) -> String {
        let values = try? url.resourceValues(forKeys: [.fileSizeKey, .contentModificationDateKey])
        return "\(url.path)|\(values?.fileSize ?? -1)|\(values?.contentModificationDate?.timeIntervalSince1970 ?? 0)"
    }

    /** Files copied in Finder: each regular file joins the list once its hash is known. */
    private func copiedFiles(_ urls: [URL]) {
        for url in urls {
            let values = try? url.resourceValues(forKeys: [.isRegularFileKey, .fileSizeKey])
            guard values?.isRegularFile == true, let size = values?.fileSize, Int64(size) <= Model.maxFile else { continue }
            let key = fileKey(url)
            let mime = UTType(filenameExtension: url.pathExtension)?.preferredMIMEType ?? "application/octet-stream"
            let finish: (String) -> Void = { [weak self] id in
                guard let self else { return }
                self.fileIds[key] = id
                let item = self.store.copiedHere(file: url, id: id, size: Int64(size), mime: mime)
                self.link.broadcast(SyncMessage(t: "upsert", item: item, fresh: true))
            }
            if let id = fileIds[key] {
                finish(id)
            } else {
                DispatchQueue.global(qos: .userInitiated).async {
                    guard let handle = try? FileHandle(forReadingFrom: url) else { return }
                    var hasher = SHA256()
                    while true {
                        let chunk = handle.readData(ofLength: 1024 * 1024)
                        if chunk.isEmpty { break }
                        hasher.update(data: chunk)
                    }
                    try? handle.close()
                    let id = "f" + String(hasher.finalize().map { String(format: "%02x", $0) }.joined().prefix(32))
                    DispatchQueue.main.async { finish(id) }
                }
            }
        }
    }

    // MARK: the Mac's clipboard

    private func checkPasteboard() {
        let pasteboard = NSPasteboard.general
        let change = pasteboard.changeCount
        guard change != lastChange else { return }
        lastChange = change
        if change == ownChange { return }
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        if !types.isDisjoint(with: Model.skippedTypes) { return }
        // a file copied in Finder also carries its name as text and its icon as a picture: take the file
        if types.contains(NSPasteboard.PasteboardType.fileURL.rawValue) {
            let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL] ?? []
            copiedFiles(urls)
            return
        }
        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            guard text.utf8.count <= 4_000_000 else { return }
            let item = store.copiedHere(text)
            link.broadcast(SyncMessage(t: "upsert", item: item, fresh: true))
        } else if let (data, mime) = picture(on: pasteboard), data.count <= Model.maxPicture {
            let item = store.copiedHere(image: data, mime: mime)
            link.broadcast(SyncMessage(t: "upsert", item: item, fresh: true))
        }
    }

    /** The picture on the clipboard as PNG or JPEG bytes, unchanged when it already is one. */
    private func picture(on pasteboard: NSPasteboard) -> (Data, String)? {
        if let png = pasteboard.data(forType: .png) { return (png, "image/png") }
        if let jpeg = pasteboard.data(forType: Model.jpeg) { return (jpeg, "image/jpeg") }
        if let tiff = pasteboard.data(forType: .tiff),
           let png = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:]) {
            return (png, "image/png")
        }
        return nil
    }

    private func put(_ item: SyncItem, own: Bool) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        if item.kind == "file" {
            // the file itself: Cmd+V in Finder copies it, a chat app attaches it
            guard let url = store.fileURL(item.id) else { return }
            pasteboard.writeObjects([url as NSURL])
        } else if item.kind == "image" {
            guard let data = store.blob(item.id) else { return }
            let type: NSPasteboard.PasteboardType = item.mime == "image/jpeg" ? Model.jpeg : .png
            pasteboard.setData(data, forType: type)
            // apps that only read TIFF still get the picture
            if let tiff = NSImage(data: data)?.tiffRepresentation { pasteboard.setData(tiff, forType: .tiff) }
        } else {
            pasteboard.setString(item.text, forType: .string)
        }
        if own {
            ownChange = pasteboard.changeCount
            lastChange = ownChange
        }
    }

    // MARK: the list's buttons

    /** Copies an item here; it then counts as a new copy and moves to the top on both sides. */
    func copy(_ item: SyncItem) {
        put(item, own: false)
        copiedId = item.id
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.2) { [weak self] in
            if self?.copiedId == item.id { self?.copiedId = nil }
        }
    }

    func togglePin(_ item: SyncItem) {
        guard let changed = store.togglePin(item.id) else { return }
        link.broadcast(SyncMessage(t: "upsert", item: changed, fresh: false))
    }

    func delete(_ item: SyncItem) {
        let marks = store.delete([item.id])
        if !marks.isEmpty { link.broadcast(SyncMessage(t: "gone", gone: marks)) }
    }

    func clear() {
        let marks = store.clearUnpinned()
        if !marks.isEmpty { link.broadcast(SyncMessage(t: "gone", gone: marks)) }
    }

    func newCode() {
        code = PairingCode.make()
        try? code.write(to: folder.appendingPathComponent("pairing-code.txt"), atomically: true, encoding: .utf8)
        link.rekey(code)
    }
}

@main
struct EvaBoardMacApp: App {
    @ObservedObject private var model = Model.shared

    var body: some Scene {
        MenuBarExtra {
            ContentView()
                .environmentObject(model)
                .environmentObject(model.store)
                .environmentObject(model.link)
        } label: {
            Image(systemName: "list.clipboard")
        }
        .menuBarExtraStyle(.window)
    }
}

struct ContentView: View {
    @EnvironmentObject private var model: Model
    @EnvironmentObject private var store: Store
    @EnvironmentObject private var link: Link
    @State private var showCode = false
    @State private var listHeight: CGFloat = 0
    @State private var launchAtLogin = SMAppService.mainApp.status == .enabled

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            header
                .padding(.horizontal, 16)
                .padding(.top, 14)
                .padding(.bottom, 10)

            if link.phones.isEmpty || showCode {
                codePanel
                    .padding(.horizontal, 12)
                    .padding(.bottom, 10)
            }

            if store.items.isEmpty {
                Text("Тут зʼявиться все, що ви копіюєте на телефоні й на Mac")
                    .font(.system(size: 13))
                    .foregroundStyle(.secondary)
                    .frame(maxWidth: .infinity, minHeight: 120)
                    .multilineTextAlignment(.center)
                    .padding(.horizontal, 24)
            } else {
                // A scroll view in a menu-bar window has no height of its own and shrinks to nothing:
                // it gets the height of its rows, up to a limit, measured from the rows themselves.
                ScrollView {
                    VStack(spacing: 6) {
                        ForEach(store.sorted) { item in
                            ItemRow(item: item)
                        }
                    }
                    .padding(.horizontal, 12)
                    .padding(.vertical, 4)
                    .background(GeometryReader { geometry in
                        Color.clear.preference(key: ListHeight.self, value: geometry.size.height)
                    })
                }
                .frame(height: min(max(listHeight, 60), 480))
                .onPreferenceChange(ListHeight.self) { listHeight = $0 }
            }

            Divider().padding(.top, 8)
            footer
                .padding(.horizontal, 12)
                .padding(.vertical, 8)
        }
        .frame(width: 360)
    }

    private var header: some View {
        HStack(spacing: 8) {
            Text("Буфер обміну").font(.system(size: 15, weight: .semibold))
            Spacer()
            Circle()
                .fill(link.phones.isEmpty ? Color.secondary.opacity(0.5) : Color.green)
                .frame(width: 7, height: 7)
            Text(link.phones.isEmpty ? "Телефон не підключено" : link.phones.joined(separator: ", "))
                .font(.system(size: 12))
                .foregroundStyle(.secondary)
                .lineLimit(1)
        }
    }

    private var codePanel: some View {
        VStack(alignment: .leading, spacing: 6) {
            Text("Код для телефону").font(.system(size: 12, weight: .medium)).foregroundStyle(.secondary)
            Text(model.code)
                .font(.system(size: 20, weight: .semibold, design: .monospaced))
                .textSelection(.enabled)
            Text("evaBoard → Налаштування → «Буфер обміну на Mac». Телефон і Mac мають бути в одній мережі Wi-Fi.")
                .font(.system(size: 11))
                .foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)
            if let problem = link.problem {
                Text(problem).font(.system(size: 11)).foregroundStyle(.red)
            }
        }
        .padding(12)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(RoundedRectangle(cornerRadius: 12).fill(Color.primary.opacity(0.05)))
    }

    private var footer: some View {
        HStack {
            Button {
                model.clear()
            } label: {
                Label("Очистити", systemImage: "trash")
            }
            .buttonStyle(.borderless)
            .disabled(store.items.values.allSatisfy(\.pinned))
            .help("Видаляє все, крім закріпленого, - і тут, і на телефоні")

            Spacer()

            Menu {
                Button(showCode ? "Сховати код" : "Показати код для телефону") { showCode.toggle() }
                Button("Новий код (телефон треба буде підключити знову)") { model.newCode() }
                Divider()
                Toggle("Запускати разом з Mac", isOn: Binding(get: { launchAtLogin }, set: { on in
                    do {
                        if on { try SMAppService.mainApp.register() } else { try SMAppService.mainApp.unregister() }
                    } catch {}
                    launchAtLogin = SMAppService.mainApp.status == .enabled
                }))
                Divider()
                Button("Вийти з evaBoard") { NSApp.terminate(nil) }
            } label: {
                Image(systemName: "ellipsis.circle")
            }
            .menuStyle(.borderlessButton)
            .menuIndicator(.hidden)
            .fixedSize()
        }
    }
}

struct ItemRow: View {
    let item: SyncItem
    @EnvironmentObject private var model: Model
    @State private var hover = false

    var body: some View {
        HStack(alignment: .top, spacing: 8) {
            VStack(alignment: .leading, spacing: 3) {
                if item.kind == "image" {
                    Thumbnail(id: item.id)
                } else if item.kind == "file" {
                    FileLine(item: item)
                } else {
                    Text(item.text.trimmingCharacters(in: .whitespacesAndNewlines))
                        .font(.system(size: 13))
                        .lineLimit(3)
                        .frame(maxWidth: .infinity, alignment: .leading)
                }
                Text(model.copiedId == item.id ? "Скопійовано" : when(item.ts))
                    .font(.system(size: 11))
                    .foregroundStyle(model.copiedId == item.id ? Color.accentColor : .secondary)
            }
            if hover || item.pinned {
                Button { model.togglePin(item) } label: {
                    Image(systemName: item.pinned ? "pin.fill" : "pin")
                }
                .buttonStyle(.borderless)
                .help(item.pinned ? "Відкріпити" : "Закріпити")
            }
            if hover {
                Button { model.delete(item) } label: { Image(systemName: "xmark") }
                    .buttonStyle(.borderless)
                    .help("Видалити")
            }
        }
        .padding(.horizontal, 10)
        .padding(.vertical, 8)
        .background(RoundedRectangle(cornerRadius: 10).fill(Color.primary.opacity(hover ? 0.09 : 0.045)))
        .contentShape(Rectangle())
        .onHover { hover = $0 }
        .onTapGesture { model.copy(item) }
    }

    private func when(_ ts: Int64) -> String {
        let date = Date(timeIntervalSince1970: TimeInterval(ts) / 1000)
        let formatter = RelativeDateTimeFormatter()
        formatter.locale = Locale(identifier: "uk_UA")
        formatter.unitsStyle = .short
        return formatter.localizedString(for: date, relativeTo: Date())
    }
}

/** A picture in the list, read once from its file and kept. */
struct Thumbnail: View {
    let id: String
    @EnvironmentObject private var store: Store
    private static let cache = NSCache<NSString, NSImage>()

    var body: some View {
        if let image = load() {
            Image(nsImage: image)
                .resizable()
                .aspectRatio(contentMode: .fit)
                .frame(maxWidth: .infinity, maxHeight: 130, alignment: .leading)
                .clipShape(RoundedRectangle(cornerRadius: 8))
        } else {
            Text("Картинка ще йде з телефону…")
                .font(.system(size: 12))
                .foregroundStyle(.secondary)
                .frame(maxWidth: .infinity, alignment: .leading)
        }
    }

    private func load() -> NSImage? {
        if let cached = Thumbnail.cache.object(forKey: id as NSString) { return cached }
        guard store.hasBlob(id), let image = NSImage(contentsOf: store.blobURL(id)) else { return nil }
        Thumbnail.cache.setObject(image, forKey: id as NSString)
        return image
    }
}

private struct ListHeight: PreferenceKey {
    static var defaultValue: CGFloat = 0
    static func reduce(value: inout CGFloat, nextValue: () -> CGFloat) { value = max(value, nextValue()) }
}

/** A file in the list: its icon, name and size, and a way to it in Finder. */
struct FileLine: View {
    let item: SyncItem
    @EnvironmentObject private var store: Store

    var body: some View {
        let url = store.fileURL(item.id)
        HStack(spacing: 10) {
            Image(nsImage: url.map { NSWorkspace.shared.icon(forFile: $0.path) } ?? NSWorkspace.shared.icon(for: .data))
                .resizable()
                .frame(width: 32, height: 32)
            VStack(alignment: .leading, spacing: 2) {
                Text(item.text).font(.system(size: 13)).lineLimit(2)
                Text(url == nil ? "Ще йде з телефону…" : sizeText)
                    .font(.system(size: 11))
                    .foregroundStyle(.secondary)
            }
            Spacer(minLength: 0)
            if let url {
                Button { NSWorkspace.shared.activateFileViewerSelecting([url]) } label: { Image(systemName: "folder") }
                    .buttonStyle(.borderless)
                    .help("Показати у Finder")
            }
        }
    }

    private var sizeText: String {
        ByteCountFormatter.string(fromByteCount: item.size ?? 0, countStyle: .file)
    }
}
