# Regenerates app/src/main/kotlin/dev/patrickgold/florisboard/ime/eva/LucideData.kt
# from lucide-static (the same icon set mindEva uses), keeping only the icons listed in ICONS.
#   cd <scratch> && npm pack lucide-static && tar xzf lucide-static-*.tgz
#   python3 evaboard/tools/gen-lucide-icons.py <scratch>/package
import json, os, sys

ICONS = """arrow-left arrow-right arrow-up arrow-down copy scissors clipboard-paste lasso-select eraser
delete corner-down-left check search send arrow-big-up arrow-big-up-dash face-slightly-smiling clipboard
globe settings undo-2 redo-2 ellipsis venetian-mask eye spell-check smartphone mic chevron-down keyboard
layout-grid panel-top-close panel-top-open hash wrench arrow-left-to-line arrow-right-to-line link toggle-left toggle-right trash type image film pin pin-off video""".split()

pkg = sys.argv[1]
nodes = json.load(open(os.path.join(pkg, 'icon-nodes.json')))
missing = [i for i in ICONS if i not in nodes]
if missing:
    sys.exit('not in lucide: ' + ', '.join(missing))
lic = open(os.path.join(pkg, 'LICENSE')).read().strip()


def num(v):
    f = float(v)
    return str(int(f)) if f == int(f) else ('%.4f' % f).rstrip('0').rstrip('.')


def to_path(tag, a):
    if tag == 'path':
        return a['d']
    if tag in ('circle', 'ellipse'):
        cx, cy = float(a['cx']), float(a['cy'])
        rx = float(a['r']) if tag == 'circle' else float(a['rx'])
        ry = rx if tag == 'circle' else float(a['ry'])
        return (f"M{num(cx - rx)} {num(cy)}a{num(rx)} {num(ry)} 0 1 0 {num(2 * rx)} 0"
                f"a{num(rx)} {num(ry)} 0 1 0 {num(-2 * rx)} 0z")
    if tag == 'rect':
        x, y, w, h = (float(a.get(k, 0)) for k in ('x', 'y', 'width', 'height'))
        rx = float(a.get('rx', a.get('ry', 0)))
        ry = float(a.get('ry', rx))
        if rx == 0 and ry == 0:
            return f"M{num(x)} {num(y)}h{num(w)}v{num(h)}h{num(-w)}z"
        return (f"M{num(x + rx)} {num(y)}h{num(w - 2 * rx)}a{num(rx)} {num(ry)} 0 0 1 {num(rx)} {num(ry)}"
                f"v{num(h - 2 * ry)}a{num(rx)} {num(ry)} 0 0 1 {num(-rx)} {num(ry)}"
                f"h{num(-(w - 2 * rx))}a{num(rx)} {num(ry)} 0 0 1 {num(-rx)} {num(-ry)}"
                f"v{num(-(h - 2 * ry))}a{num(rx)} {num(ry)} 0 0 1 {num(rx)} {num(-ry)}z")
    if tag == 'line':
        return f"M{num(a['x1'])} {num(a['y1'])}L{num(a['x2'])} {num(a['y2'])}"
    if tag in ('polyline', 'polygon'):
        pts = a['points'].replace(',', ' ').split()
        pairs = [f"{num(pts[i])} {num(pts[i + 1])}" for i in range(0, len(pts), 2)]
        return 'M' + 'L'.join(pairs) + ('z' if tag == 'polygon' else '')
    sys.exit('unsupported element ' + tag)


out = ['// GENERATED by evaboard/tools/gen-lucide-icons.py from lucide-static - only the icons evaBoard\n'
       '// uses. Regenerate rather than hand-edit.\n//\n// Lucide - https://lucide.dev\n//\n',
       '/*\n' + lic + '\n*/\n\n',
       'package dev.patrickgold.florisboard.ime.eva\n\n',
       '/** Lucide icon name -> its shapes as SVG path data (24x24 grid, stroke 2, round caps and joins). */\n',
       'internal val LUCIDE_PATHS: Map<String, List<String>> = mapOf(\n']
for name in sorted(ICONS):
    paths = [to_path(tag, attrs) for tag, attrs in nodes[name]]
    out.append(f'    "{name}" to listOf(\n' + ''.join(f'        "{p}",\n' for p in paths) + '    ),\n')
out.append(')\n')
dest = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'app', 'src', 'main', 'kotlin',
                    'dev', 'patrickgold', 'florisboard', 'ime', 'eva', 'LucideData.kt')
open(dest, 'w').write(''.join(out))
print('wrote', os.path.normpath(dest), len(ICONS), 'icons')
