// THE ICONS ON OFFER, BY THEME (2026-10-02: "розширити кількість піктограм
// ... розділити за тематикою"). 'lc:<name>' draws that Lucide icon straight
// (the generated set carries it - scripts/lucide-map.py EXTRA); a plain name
// is an Ionicons name as before (the earlier set, and the brands - Lucide
// has no logos, so those keep Ionicons' own drawing).

import { TAG_ICONS } from './tags';

export type IconCategory = { label: string; icons: string[] };

export const ICON_CATEGORIES: IconCategory[] = [
  { label: "Застосунки й техніка", icons: ['lc:smartphone', 'lc:tablet', 'lc:laptop', 'lc:monitor', 'lc:tv', 'lc:app-window', 'lc:package', 'lc:package-open', 'lc:bot', 'lc:cpu', 'lc:hard-drive', 'lc:server', 'lc:database', 'lc:cloud', 'lc:wifi', 'lc:bluetooth', 'lc:battery-charging', 'lc:plug', 'lc:usb', 'lc:cable', 'lc:code', 'lc:terminal', 'lc:braces', 'lc:bug', 'lc:git-branch', 'lc:git-fork', 'lc:layout-grid', 'lc:layout-dashboard', 'lc:puzzle', 'lc:download', 'lc:upload', 'lc:qr-code', 'lc:scan-line', 'lc:smartphone-nfc', 'lc:watch', 'lc:headphones', 'lc:gamepad-2', 'lc:printer', 'lc:keyboard', 'lc:mouse', 'lc:webcam', 'lc:router', 'lc:satellite-dish', 'lc:radio'] },
  { label: "Робота", icons: ['lc:briefcase', 'lc:building', 'lc:landmark', 'lc:presentation', 'lc:chart-column', 'lc:chart-pie', 'lc:trending-up', 'lc:target', 'lc:clipboard-list', 'lc:clipboard-check', 'lc:list-todo', 'lc:kanban', 'lc:calendar', 'lc:calendar-days', 'lc:calendar-clock', 'lc:clock', 'lc:timer', 'lc:alarm-clock', 'lc:mail', 'lc:send', 'lc:inbox', 'lc:file-text', 'lc:files', 'lc:folder', 'lc:folder-open', 'lc:archive', 'lc:stamp', 'lc:signature', 'lc:pen-tool', 'lc:pencil', 'lc:highlighter', 'lc:paperclip', 'lc:pin', 'lc:handshake', 'lc:award', 'lc:badge-check'] },
  { label: "Дім", icons: ['lc:house', 'lc:sofa', 'lc:bed', 'lc:bath', 'lc:lamp', 'lc:lightbulb', 'lc:key-round', 'lc:lock', 'lc:door-open', 'lc:armchair', 'lc:washing-machine', 'lc:refrigerator', 'lc:microwave', 'lc:cooking-pot', 'lc:utensils', 'lc:trash', 'lc:shower-head', 'lc:fence', 'lc:warehouse', 'lc:tent', 'lc:flower-2', 'lc:trees'] },
  { label: "Гроші", icons: ['lc:wallet', 'lc:banknote', 'lc:coins', 'lc:credit-card', 'lc:piggy-bank', 'lc:receipt', 'lc:percent', 'lc:calculator', 'lc:chart-line', 'lc:dollar-sign', 'lc:euro', 'lc:hand-coins', 'lc:landmark', 'lc:scale', 'lc:gem', 'lc:shopping-cart', 'lc:shopping-bag', 'lc:store', 'lc:tag', 'lc:gift', 'lc:ticket'] },
  { label: "Транспорт", icons: ['lc:car', 'lc:car-front', 'lc:bus', 'lc:train-front', 'lc:tram-front', 'lc:plane', 'lc:sailboat', 'lc:ship', 'lc:bike', 'lc:motorbike', 'lc:truck', 'lc:tractor', 'lc:fuel', 'lc:route', 'lc:map', 'lc:map-pin', 'lc:navigation', 'lc:compass', 'lc:parking-meter', 'lc:traffic-cone', 'lc:rocket'] },
  { label: "Їжа", icons: ['lc:coffee', 'lc:cup-soda', 'lc:wine', 'lc:beer', 'lc:pizza', 'lc:sandwich', 'lc:salad', 'lc:soup', 'lc:apple', 'lc:cherry', 'lc:carrot', 'lc:egg', 'lc:fish', 'lc:beef', 'lc:croissant', 'lc:cake-slice', 'lc:ice-cream-cone', 'lc:candy', 'lc:cookie', 'lc:milk', 'lc:utensils-crossed', 'lc:chef-hat'] },
  { label: "Навчання", icons: ['lc:book-open', 'lc:book', 'lc:library', 'lc:graduation-cap', 'lc:notebook-pen', 'lc:school', 'lc:backpack', 'lc:lightbulb', 'lc:brain', 'lc:atom', 'lc:flask-conical', 'lc:microscope', 'lc:telescope', 'lc:globe', 'lc:languages', 'lc:spell-check', 'lc:ruler', 'lc:shapes', 'lc:sigma'] },
  { label: "Медіа", icons: ['lc:image', 'lc:images', 'lc:camera', 'lc:video', 'lc:film', 'lc:clapperboard', 'lc:music', 'lc:headphones', 'lc:mic', 'lc:radio', 'lc:rss', 'lc:tv-minimal', 'lc:play', 'lc:tv-minimal-play', 'lc:book-audio', 'lc:palette', 'lc:brush', 'lc:paintbrush', 'lc:pen-line', 'lc:drama'] },
  { label: "Здоров'я й спорт", icons: ['lc:heart', 'lc:heart-pulse', 'lc:activity', 'lc:stethoscope', 'lc:pill', 'lc:syringe', 'lc:hospital', 'lc:bandage', 'lc:brain', 'lc:dumbbell', 'lc:bike', 'lc:volleyball', 'lc:trophy', 'lc:medal', 'lc:timer', 'lc:footprints', 'lc:person-standing', 'lc:baby', 'lc:apple', 'lc:salad', 'lc:moon'] },
  { label: "Подорожі", icons: ['lc:plane', 'lc:luggage', 'lc:tent', 'lc:mountain', 'lc:mountain-snow', 'lc:tree-palm', 'lc:waves-horizontal', 'lc:sun', 'lc:umbrella', 'lc:map', 'lc:compass', 'lc:globe', 'lc:hotel', 'lc:camera', 'lc:ticket', 'lc:id-card', 'lc:earth'] },
  { label: "Природа", icons: ['lc:leaf', 'lc:trees', 'lc:tree-pine', 'lc:flower', 'lc:sprout', 'lc:cloud', 'lc:cloud-rain', 'lc:cloud-snow', 'lc:sun', 'lc:moon', 'lc:star', 'lc:snowflake', 'lc:droplet', 'lc:flame', 'lc:wind', 'lc:rainbow', 'lc:bird', 'lc:cat', 'lc:dog', 'lc:fish', 'lc:rabbit', 'lc:bug', 'lc:paw-print', 'lc:shell'] },
  { label: "Люди", icons: ['lc:user', 'lc:users', 'lc:user-round', 'lc:baby', 'lc:face-slightly-smiling', 'lc:face-grinning', 'lc:face-slightly-frowning', 'lc:hand', 'lc:hand-heart', 'lc:heart-handshake', 'lc:contact', 'lc:message-circle', 'lc:messages-square', 'lc:phone', 'lc:at-sign', 'lc:crown', 'lc:glasses', 'lc:shirt'] },
  { label: "Символи", icons: ['lc:star', 'lc:sparkles', 'lc:zap', 'lc:flag', 'lc:bookmark', 'lc:tag', 'lc:hash', 'lc:asterisk', 'lc:infinity', 'lc:circle', 'lc:square', 'lc:triangle', 'lc:hexagon', 'lc:diamond', 'lc:shield', 'lc:shield-check', 'lc:lock-keyhole', 'lc:bell', 'lc:eye', 'lc:check', 'lc:x', 'lc:plus', 'lc:minus', 'lc:info', 'lc:circle-alert', 'lc:circle-question-mark'] },
  { label: 'Бренди', icons: ['logo-android', 'logo-apple', 'logo-google', 'logo-youtube', 'logo-tiktok', 'logo-instagram', 'logo-facebook', 'logo-twitter', 'logo-x', 'logo-github', 'logo-windows', 'logo-chrome', 'logo-firefox', 'logo-edge', 'logo-whatsapp', 'logo-skype', 'logo-slack', 'logo-discord', 'logo-twitch', 'logo-linkedin', 'logo-pinterest', 'logo-reddit', 'logo-figma', 'logo-dropbox', 'logo-paypal', 'logo-amazon', 'logo-steam', 'logo-playstation', 'logo-xbox', 'logo-soundcloud', 'logo-vimeo', 'logo-npm', 'logo-python', 'logo-javascript', 'logo-react', 'logo-electron', 'logo-firebase', 'logo-docker', 'logo-tux', 'logo-vk', 'logo-wechat', 'logo-snapchat', 'logo-tumblr', 'logo-behance', 'logo-dribbble', 'logo-codepen', 'logo-mastodon', 'logo-threads', 'logo-bitcoin', 'logo-stackoverflow', 'logo-medium'] },
  // Everything offered before - kept, so a folder that already wears one
  // finds it here.
  { label: 'Інші', icons: TAG_ICONS },
];

