// Colors offered when creating a tag - same swatch-picker pattern as
// TasksScreen's PROJECT_COLORS. The harmonious muted palette from the
// gradient-analysis reference, also used for the random document-card
// color in documentColor.ts - one palette across the app's warm redesign
// rather than a separate bright set just for tags.
export const TAG_COLORS = [
  '#DAA587', // Теплий Бежевий
  '#84B799', // М'який Шорсткий Зелений
  '#BE7657', // Теплий Теракотовий
  '#69736E', // М'який Сірий Гекс
  '#A0B4AF', // Блідо-М'ятний Зелений
  '#556E78', // Глибокий Шорсткий Зелений
  '#788782', // М'який Блідий Шорсткий Зелений
];

// A curated set of Ionicons outline glyphs offered when creating a tag -
// not the full ~1300-icon library (no search-the-whole-set UI yet), but
// enough variety across common tagging themes that a name search over this
// list finds something reasonable. All names are real Ionicons outline
// glyphs, already available via @expo/vector-icons with no new dependency.
export const TAG_ICONS: string[] = [
  'pricetag-outline',
  'briefcase-outline',
  'home-outline',
  'business-outline',
  'storefront-outline',
  'construct-outline',
  'hammer-outline',
  'build-outline',
  'settings-outline',
  'bulb-outline',
  'flash-outline',
  'battery-charging-outline',
  'key-outline',
  'lock-closed-outline',
  'lock-open-outline',
  'shield-outline',
  'shield-checkmark-outline',
  'car-outline',
  'airplane-outline',
  'boat-outline',
  'bicycle-outline',
  'bus-outline',
  'train-outline',
  'subway-outline',
  'walk-outline',
  'restaurant-outline',
  'cafe-outline',
  'wine-outline',
  'beer-outline',
  'pizza-outline',
  'fast-food-outline',
  'nutrition-outline',
  'ice-cream-outline',
  'cart-outline',
  'bag-outline',
  'gift-outline',
  'cash-outline',
  'card-outline',
  'wallet-outline',
  'calculator-outline',
  'trending-up-outline',
  'trending-down-outline',
  'stats-chart-outline',
  'bar-chart-outline',
  'pie-chart-outline',
  'receipt-outline',
  'medical-outline',
  'medkit-outline',
  'fitness-outline',
  'barbell-outline',
  'body-outline',
  'heart-outline',
  'pulse-outline',
  'thermometer-outline',
  'bandage-outline',
  'school-outline',
  'book-outline',
  'library-outline',
  'pencil-outline',
  'create-outline',
  'brush-outline',
  'color-palette-outline',
  'camera-outline',
  'videocam-outline',
  'film-outline',
  'musical-notes-outline',
  'mic-outline',
  'headset-outline',
  'radio-outline',
  'tv-outline',
  'game-controller-outline',
  'dice-outline',
  'football-outline',
  'basketball-outline',
  'tennisball-outline',
  'golf-outline',
  'trophy-outline',
  'medal-outline',
  'ribbon-outline',
  'flag-outline',
  'flame-outline',
  'water-outline',
  'snow-outline',
  'sunny-outline',
  'moon-outline',
  'cloud-outline',
  'thunderstorm-outline',
  'rainy-outline',
  'partly-sunny-outline',
  'leaf-outline',
  'flower-outline',
  'paw-outline',
  'fish-outline',
  'bug-outline',
  'planet-outline',
  'earth-outline',
  'globe-outline',
  'map-outline',
  'location-outline',
  'navigate-outline',
  'compass-outline',
  'pin-outline',
  'bed-outline',
  'laptop-outline',
  'desktop-outline',
  'phone-portrait-outline',
  'tablet-portrait-outline',
  'print-outline',
  'wifi-outline',
  'bluetooth-outline',
  'hardware-chip-outline',
  'server-outline',
  'cloud-upload-outline',
  'cloud-download-outline',
  'link-outline',
  'attach-outline',
  'document-outline',
  'document-text-outline',
  'folder-outline',
  'folder-open-outline',
  'archive-outline',
  'mail-outline',
  'chatbubble-outline',
  'chatbox-outline',
  'call-outline',
  'people-outline',
  'person-outline',
  'person-add-outline',
  'happy-outline',
  'sad-outline',
  'star-outline',
  'alarm-outline',
  'time-outline',
  'calendar-outline',
  'hourglass-outline',
  'stopwatch-outline',
  'checkmark-circle-outline',
  'warning-outline',
  'information-circle-outline',
  'help-circle-outline',
  'list-outline',
  'grid-outline',
  'apps-outline',
  'layers-outline',
  'cube-outline',
  'extension-puzzle-outline',
  'rocket-outline',
  'telescope-outline',
  'flask-outline',
  'egg-outline',
  'umbrella-outline',
  'glasses-outline',
  'shirt-outline',
  'cut-outline',
  'diamond-outline',
  'sparkles-outline',
  'magnet-outline',
  'infinite-outline',
];
