# Ionicons name (without -outline) -> lucide name [, mode]
M = {
'add':'plus','add-circle':'circle-plus','airplane':'plane','alarm':'alarm-clock','albums':'gallery-vertical-end',
'apps':'layout-grid','archive':'archive','arrow-back':'arrow-left','arrow-down':'arrow-down','arrow-forward':'arrow-right',
'arrow-up':'arrow-up','arrow-redo':'redo-2','arrow-undo':'undo-2','attach':'paperclip','bag':'shopping-bag',
'bandage':'bandage','bar-chart':'chart-column','barbell':'dumbbell','basketball':'volleyball','battery-charging':'battery-charging',
'bed':'bed','beer':'beer','bicycle':'bike','bluetooth':'bluetooth','boat':'sailboat','body':'person-standing',
'book':'book-open','bookmark':'bookmark','bookmarks':'library','briefcase':'briefcase','brush':'brush','bug':'bug',
'build':'wrench','bulb':'lightbulb','bus':'bus','business':'building','cafe':'coffee','calculator':'calculator',
'calendar':'calendar','call':'phone','camera':'camera','car':'car','card':'credit-card','cart':'shopping-cart',
'cash':'banknote','chatbox':'message-square','chatbubble':'message-circle','chatbubbles':'messages-square',
'checkbox':'square-check','checkmark':'check','checkmark-circle':'circle-check','checkmark-done':'check-check',
'chevron-back':'chevron-left','chevron-down':'chevron-down','chevron-forward':'chevron-right','chevron-up':'chevron-up',
'chevron-down-circle':'circle-chevron-down','clipboard':'clipboard','close':'x','code':'code','code-slash':'code',
'color-fill':'paint-bucket','color-palette':'palette','compass':'compass','construct':'construction','contract':'minimize-2',
'copy':'copy','browsers':'columns-2','newspaper':'columns-3','calendar-number':'calendar-range','duplicate':'copy-plus','create':'square-pen','crop':'crop','cube':'box','cut':'scissors','desktop':'monitor','diamond':'gem',
'dice':'dice-5','document':'file','documents':'files','document-text':'file-text','download':'download','earth':'earth',
'easel':'presentation','egg':'egg','ellipse':'circle','ellipsis-horizontal':'ellipsis','expand':'maximize-2',
'extension-puzzle':'puzzle','eye-off':'eye-off','eye':'eye','fast-food':'hamburger','film':'film','filter':'list-filter',
'fish':'fish','fitness':'heart-pulse','flag':'flag','flame':'flame','flash':'zap','flask':'flask-conical','flower':'flower-2',
'folder':'folder','folder-open':'folder-open','football':'goal','funnel':'funnel','game-controller':'gamepad-2','gift':'gift',
'git-merge':'git-merge','git-network':'network','glasses':'glasses','globe':'globe','golf':'flag-triangle-right',
'grid':'layout-grid','hammer':'hammer','happy':'face-slightly-smiling','hardware-chip':'cpu','headset':'headphones','heart':'heart',
'help-circle':'circle-question-mark','home':'house','hourglass':'hourglass','ice-cream':'ice-cream-cone','image':'image',
'images':'images','infinite':'infinity','information-circle':'info','key':'key-round','laptop':'laptop','layers':'layers',
'leaf':'leaf','library':'library','link':'link','list':'list','list-circle':'list-ordered','locate':'locate-fixed',
'location':'map-pin','lock-closed':'lock','lock-open':'lock-open','magnet':'magnet','mail':'mail','map':'map',
'medal':'medal','medical':'stethoscope','medkit':'briefcase-medical','menu':'menu','mic':'mic','moon':'moon','move':'move',
'musical-notes':'music','navigate':'navigation','notifications':'bell','nutrition':'apple','open':'external-link',
'options':'sliders-horizontal','partly-sunny':'cloud-sun','paw':'paw-print','pencil':'pencil','people':'users',
'person-add':'user-plus','person-circle':'circle-user','person':'user','phone-portrait':'smartphone','pie-chart':'chart-pie',
'pin':'pin','pizza':'pizza','planet':'orbit','play-circle':'circle-play','play':'play','pricetag':'tag','print':'printer',
'pulse':'activity','radio-button-off':'circle','radio-button-on':'circle-dot','radio':'radio','rainy':'cloud-rain',
'reader':'scroll-text','receipt':'receipt','refresh':'rotate-cw','remove':'minus','remove-circle':'circle-minus',
'reorder-four':'text-align-justify','reorder-two':'equal','resize':'move-diagonal-2','restaurant':'utensils',
'return-down-back':'corner-down-left','ribbon':'award','rocket':'rocket','sad':'face-slightly-frowning','save':'save','scale':'scale',
'scan':'scan','school':'graduation-cap','search':'search','server':'server','settings':'settings','shapes':'shapes',
'share':'share','share-social':'share-2','shield-checkmark':'shield-check','shield':'shield','shirt':'shirt',
'snow':'snowflake','sparkles':'sparkles','square':'square','star':'star','stats-chart':'chart-no-axes-column',
'stop':'square','stopwatch':'timer','storefront':'store','subway':'train-front-tunnel','sunny':'sun',
'swap-horizontal':'arrow-left-right','swap-vertical':'arrow-up-down','tablet-landscape':'tablet','tablet-portrait':'tablet',
'telescope':'telescope','tennisball':'volleyball','text':'type','thermometer':'thermometer','thunderstorm':'cloud-lightning',
'time':'clock','today':'calendar-days','toggle':'toggle-right','train':'train-front','trash':'trash',
'trending-down':'trending-down','trending-up':'trending-up','triangle':'triangle','trophy':'trophy','tv':'tv',
'umbrella':'umbrella','videocam':'video','walk':'footprints','wallet':'wallet','warning':'triangle-alert','water':'droplet',
'wifi':'wifi','wine':'wine','cloud-done':'cloud-check','cloud-download':'cloud-download','cloud-offline':'cloud-off',
'cloud':'cloud','cloud-upload':'cloud-upload','lock':'lock','send':'send','pause':'pause','add-circle-outline':'circle-plus',
'arrow-back-circle':'circle-arrow-left','close-circle':'circle-x','refresh-circle':'refresh-cw','sync':'refresh-cw',
'volume-high':'volume-2','language':'languages','swap':'arrow-left-right','albums':'gallery-vertical-end',
}
# The filled Ionicons names that mean a STATE, drawn solid; everything else outline.
SOLID = {'star':'all','heart':'all','stop':'all','checkbox':'badge','checkmark-circle':'badge','radio-button-on':'dot','close-circle':'badge'}

# Lucide icons offered by name in the icon picker (src/constants/iconCatalog.ts,
# 'lc:<name>'), beyond those standing in for an Ionicons name.
EXTRA = ['activity', 'alarm-clock', 'app-window', 'apple', 'archive', 'armchair', 'asterisk', 'at-sign', 'atom', 'award', 'baby', 'backpack', 'badge-check', 'bandage', 'banknote', 'bath', 'battery-charging', 'bed', 'beef', 'beer', 'bell', 'bike', 'bird', 'bluetooth', 'book', 'book-audio', 'book-open', 'bookmark', 'bot', 'braces', 'brain', 'briefcase', 'brush', 'bug', 'building', 'bus', 'cable', 'cake-slice', 'calculator', 'calendar', 'calendar-clock', 'calendar-days', 'camera', 'candy', 'car', 'car-front', 'carrot', 'cat', 'chart-column', 'chart-line', 'chart-pie', 'check', 'chef-hat', 'cherry', 'circle', 'circle-alert', 'circle-question-mark', 'clapperboard', 'clipboard-check', 'clipboard-list', 'clock', 'cloud', 'cloud-rain', 'cloud-snow', 'code', 'coffee', 'coins', 'compass', 'contact', 'cookie', 'cooking-pot', 'cpu', 'credit-card', 'croissant', 'crown', 'cup-soda', 'database', 'diamond', 'dog', 'dollar-sign', 'door-open', 'download', 'drama', 'droplet', 'dumbbell', 'earth', 'egg', 'euro', 'eye', 'face-grinning', 'face-slightly-frowning', 'face-slightly-smiling', 'fence', 'file-text', 'files', 'film', 'fish', 'flag', 'flame', 'flask-conical', 'flower', 'flower-2', 'folder', 'folder-open', 'footprints', 'fuel', 'gamepad-2', 'gem', 'gift', 'git-branch', 'git-fork', 'glasses', 'globe', 'graduation-cap', 'hand', 'hand-coins', 'hand-heart', 'handshake', 'hard-drive', 'hash', 'headphones', 'heart', 'heart-handshake', 'heart-pulse', 'hexagon', 'highlighter', 'hospital', 'hotel', 'house', 'ice-cream-cone', 'id-card', 'image', 'images', 'inbox', 'infinity', 'info', 'kanban', 'key-round', 'keyboard', 'lamp', 'landmark', 'languages', 'laptop', 'layout-dashboard', 'layout-grid', 'leaf', 'library', 'lightbulb', 'list-todo', 'lock', 'lock-keyhole', 'luggage', 'mail', 'map', 'map-pin', 'medal', 'message-circle', 'messages-square', 'mic', 'microscope', 'microwave', 'milk', 'minus', 'monitor', 'moon', 'motorbike', 'mountain', 'mountain-snow', 'mouse', 'music', 'navigation', 'notebook-pen', 'package', 'package-open', 'paintbrush', 'palette', 'paperclip', 'parking-meter', 'paw-print', 'pen-line', 'pen-tool', 'pencil', 'percent', 'person-standing', 'phone', 'piggy-bank', 'pill', 'pin', 'pizza', 'plane', 'play', 'plug', 'plus', 'presentation', 'printer', 'puzzle', 'qr-code', 'rabbit', 'radio', 'rainbow', 'receipt', 'refrigerator', 'rocket', 'route', 'router', 'rss', 'ruler', 'sailboat', 'salad', 'sandwich', 'satellite-dish', 'scale', 'scan-line', 'school', 'send', 'server', 'shapes', 'shell', 'shield', 'shield-check', 'ship', 'shirt', 'shopping-bag', 'shopping-cart', 'shower-head', 'sigma', 'signature', 'smartphone', 'smartphone-nfc', 'snowflake', 'sofa', 'soup', 'sparkles', 'spell-check', 'sprout', 'square', 'stamp', 'star', 'stethoscope', 'store', 'sun', 'syringe', 'tablet', 'tag', 'target', 'telescope', 'tent', 'terminal', 'ticket', 'timer', 'tractor', 'traffic-cone', 'train-front', 'tram-front', 'trash', 'tree-palm', 'tree-pine', 'trees', 'trending-up', 'triangle', 'trophy', 'truck', 'tv', 'tv-minimal', 'tv-minimal-play', 'umbrella', 'upload', 'usb', 'user', 'user-round', 'users', 'utensils', 'utensils-crossed', 'video', 'volleyball', 'wallet', 'warehouse', 'washing-machine', 'watch', 'waves-horizontal', 'webcam', 'wifi', 'wind', 'wine', 'x', 'zap']
